paths:
  # Relative paths from where the script is run
  dataset_dir: "../dataset/Toronto_3D"
  ply_filename: "L002.ply"
  result_dir: "../results"
  camera_mcap_filename: "camera_sim_v1.mcap"
  lidar_mcap_filename: "lidar_sim_v1.mcap"

world:
  # Original world coordinates
  start_pos: [627446.52, 4842790.10, 140]
  # Offset to shift the world origin as recommended by authors
  utm_offset: [627285.0, 4841948.0, 0.0]

simulation:
  duration_sec: 15
  fps: 10
  speed_mps: 15

processing:
  downsample_enabled: true
  voxel_size_m: 0.03

camera:
  width: 1280
  height: 960  #tesla cam resolution
  yaw_offset_deg: -17.0

  distortion:
    enabled: true
    # Distortion coefficients: (k1, k2, p1, p2, k3), changing k1 here for bulge effect
    D: [0.25, 0.0, 0.0, 0.0, 0.0]


lidar:
  range_m: 100.0
  points_per_second: 100000
  channels: 16
  vertical_fov_deg: [-10.0, 30.0]
  horizontal_fov_deg: [-180.0, 180.0]
  accuracy_m: 0.03

