paths:
  # Relative paths from where the script is run
  dataset_dir: "../dataset/Toronto_3D"
  ply_filename: "L002.ply"
  result_dir: "../results"
  camera_mcap_filename: "camera_sim.mcap"
  lidar_mcap_filename: "lidar_sim.mcap"


world:
  # Original world coordinates
  start_pos: [627446.52, 4842790.10, 140]
  # Offset to shift the world origin as recommended by authors
  utm_offset: [627285.0, 4841948.0, 0.0]

simulation:
  duration_sec: 15
  fps: 10
  speed_mps: 13  #30mph
  debug_viz: false

processing:
  downsample_enabled: true
  voxel_size_m: 0.1

camera:
  width: 1280 
  height: 720   
  yaw_offset_deg: -17.0
  topic: "/camera"

  distortion:
    enabled: true
    # Distortion coefficients: (k1, k2, p1, p2, k3), changing k1 here for bulge effect
    D: [0.25, 0.0, 0.0, 0.0, 0.0]


lidar:
  range_m: 50.0
  channels: 32
  vertical_fov_deg: [-10.0, 30.0]
  angle_threshold_deg: 0.5
  horizontal_bins: 2188     #700K/sec at 10Hz with 32 beams
  topic: "/lidar"

